//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("USDA Forest Service")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Landis-II-Foundation")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.1")]
[assembly: System.Reflection.AssemblyProductAttribute("Landis.Library.PnETCohorts")]
[assembly: System.Reflection.AssemblyTitleAttribute("Landis.Library.PnETCohorts-v1")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.1")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("English")]

// Generated by the MSBuild WriteCodeFragment class.

